defaults: &defaults
  working_directory: /tmp/project
  environment:
    # Required:
    DISPLAY: ":99"
    # Configurable
    ATOM_LINT_WITH_BUNDLED_NODE: "true"
    APM_TEST_PACKAGES: ""
    ATOM_CHANNEL: "stable"
  docker:
    - image: circleci/node:latest

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: ./.circleci/atom-build.sh
  publish:
    <<: *defaults
    steps:
      - checkout
      - run: ./.circleci/atom-build.sh
      - run: npm install
      - run:
          name: Publish package on apm
          command: npm run semantic-release

workflows:
  version: 2
  build-and-release:
    jobs:
      - build
      - publish:
          requires:
            - build
          filters:
            branches:
              only: master
