defaults: &defaults
  working_directory: /tmp/project
  environment:
    # Required:
    DISPLAY: ":99"
    # Configurable
    ATOM_LINT_WITH_BUNDLED_NODE: "true"
    APM_TEST_PACKAGES: ""
    ATOM_CHANNEL: "stable"
  docker:
    - image: circleci/node:latest

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: ./.circleci/atom-build.sh
  publish:
    <<: *defaults
    steps:
      - checkout
      - run: ./.circleci/atom-build.sh
      - run: npm install
      - run:
          name: Publish package on apm
          command: npm run semantic-release
  docs:
    <<: *defaults
    steps:
      - checkout
      - run: git checkout -b gh-pages
      - run: git config user.email $GITHUB_EMAIL
      - run: git config user.name $GITHUB_USERNAME
      - run: npm install
      - run: npm run docs:build
      - run: mv docs/index.html ./
      - run: git add .
      - run: git commit -m 'update docs [skip ci]'
      - run: git push -q https://${GITHUB_TOKEN}@github.com/${CIRCLE_USERNAME}/${CIRCLE_PROJECT_REPONAME}.git gh-pages --force

workflows:
  version: 2
  build-and-release:
    jobs:
      - build
      - publish:
          requires:
            - build
          filters:
            branches:
              only: master
      - docs:
          requires:
            - publish
          filters:
            branches:
              only: master
